services:
  medical-clinic-proxy:
    build: .
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/medicalclinic_proxy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    networks:
      - medicalclinic-net

  db:
    image: postgres
    environment:
      POSTGRES_DB: medical_clinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medicalclinic-net

volumes:
  postgres_data:

networks:
  medicalclinic-net: